# frozen_string_literal: true
# Here are some advanced queries to enhance your understanding of ActiveRecord.

=begin

1)Find the top 3 bestselling books of all time, considering only books that are not out of print and have received at least 10 reviews. For each book, include the title, author's full name, total number of reviews, and average rating.

2)Find the top 5 customers who have spent the most on orders in the last 6 months, considering only completed orders with a subtotal greater than $100. For each customer, include their first name, last name, total amount spent, and total number of orders placed.

3)Find the top 3 authors with the highest average ratings for their books. Consider only authors who have at least 3 books published and each book must have received at least 5 reviews. For each author, include their full name, the total number of books published, and the average rating across all their books.

4)Find the total revenue generated by the bookstore in the last year, broken down by month.

5)Find the top 5 customers who have submitted the most orders in the last 6 months. For each customer, include their first name, last name, email, total number of orders submitted, and the total amount spent.

6)Find the top 3 most reviewed books, considering only books with an average rating greater than 4.5. For each book, include the title, author's full name, total number of reviews, and average rating.

7)Find the number of customers who have never submitted an order.

8)Find the top 5 customers with the highest average order value. For each customer, include their first name, last name, email, total number of orders placed, and average order value.

9)Find the top 3 authors with the highest total revenue generated from the sales of their books. For each author, include their full name, total revenue generated, and the total number of books published.

10)Find the top 5 customers who have placed the most orders for out-of-print books. For each customer, include their first name, last name, email, total number of orders placed, and the total amount spent.

=end
